/* Auto-generated by AuthSystem - 2026-06-27T20:54:29.875Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_315d7b42-83a',
  apiKey: 'ak_development_27b4dba2674ae8d9d677dc118458f17a'
};
